import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../_components/Header";
import Footer from "../_components/Footer";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full sm:w-4/5 lg:w-3/5 max-w-1200 m-auto flex flex-col h-screen">
      <Header />
      <main className=" flex-1">{children}</main>
      <Footer />
    </div>
  );
}
